name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Publish image to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          GHCR_BOT_TOKEN: ${{ secrets.GHCR_BOT_TOKEN }}
        run: echo $GHCR_BOT_TOKEN | docker login ghcr.io -u zakodium-bot --password-stdin
      - name: Build and push the Docker image
        run: |
          IMAGE_NAME=ghcr.io/$GITHUB_REPOSITORY
          VERSION=${GITHUB_REF##*/}
          VERSION_START=${VERSION%%.*}
          docker build . -t $IMAGE_NAME
          docker push $IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:$VERSION
          docker tag $IMAGE_NAME $IMAGE_NAME:$VERSION_START
          docker push $IMAGE_NAME:$VERSION_START
